# Generated by Django 6.0.2 on 2026-03-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='số điện thoại'),
        ),
    ]
