# Generated by Django 6.0.2 on 2026-03-10 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tiêu đề')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='mô tả')),
                ('duration', models.TimeField(verbose_name='thời lượng')),
                ('poster', models.ImageField(default=None, upload_to='', verbose_name='poster')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='số phòng')),
                ('capacity', models.IntegerField(default=50, verbose_name='sức chứa')),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5, verbose_name='số ghế')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie_ticket.room')),
            ],
        ),
        migrations.CreateModel(
            name='showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='thời gian bắt đầu')),
                ('price', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='giá vé')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ticket.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ticket.room')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='giá tại thời điểm mua')),
                ('created_at', models.TimeField(verbose_name='mua tại thời điểm')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ticket.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ticket.showtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
