# Generated by Django 6.0.2 on 2026-03-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='mô tả'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='thời lượng (phút)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='giá vé'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(verbose_name='thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.TimeField(auto_now_add=True, verbose_name='mua tại thời điểm'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='giá mua'),
        ),
    ]
