# Generated by Django 6.0.2 on 2026-03-11 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ticket', '0002_alter_movie_description_alter_movie_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movie_ticket.movie'),
        ),
    ]
